theme: jekyll-theme-leap-day
title: saidqb - hanya berbagi
description: saidqb di github, berbagi pengalaman sebagai seorang programmer
github_url: https://github.com/saidqb
category-list: [laravel,php]